config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'messages#index'

  resources :messages
  resources :payments, only: %i[create]
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/inbox.rb
# frozen_string_literal: true

class Inbox < ApplicationRecord
  belongs_to :user
  has_many :messages, dependent: :restrict_with_exception

  def inbox_messages
    messages
  end
end

app/models/message.rb
# frozen_string_literal: true

class Message < ApplicationRecord
  belongs_to :inbox
  belongs_to :outbox

  before_create :patient_limit_to_doctor
  before_create :update_inbox_messages_counter

  validates :body, presence: true

  delegate :outbox_newest_message, to: :outbox

  private

  def patient_limit_to_doctor
    return if outbox_newest_message.nil?
    return if inbox.user.is_patient?

    self.inbox_id = User.default_admin.inbox.id if outbox_newest_message > 1.week.ago
  end

  def update_inbox_messages_counter
    inbox.increment!(:messages_unread_counter) if inbox.user.is_doctor?
  end
end

app/models/outbox.rb
# frozen_string_literal: true

class Outbox < ApplicationRecord
  belongs_to :user
  has_many :messages, dependent: :restrict_with_exception

  def outbox_messages
    messages
  end

  def outbox_newest_message
    messages.maximum(:created_at)
  end
end

app/models/payment.rb
# frozen_string_literal: true

class Payment < ApplicationRecord
  MODES = %w[debit_card].freeze

  belongs_to :user

  validates :mode, presence: true, inclusion: { in: MODES }

  def checkout(key)
    Provider.public_send(mode, key)
  end
end

app/models/payment/provider.rb
# frozen_string_literal: true

class Payment::Provider
  def self.debit_card(key)
    Rails.logger.info("Sent POST https://provider.com/payments/#{key}")
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_one :inbox, dependent: :restrict_with_exception
  has_one :outbox, dependent: :restrict_with_exception
  has_many :payments

  scope :patient, -> { where(is_patient: true) }
  scope :admin, -> { where(is_admin: true) }
  scope :doctor, -> { where(is_doctor: true) }

  delegate :inbox_messages, to: :inbox
  delegate :outbox_messages, to: :outbox

  def self.current
    patient.first
  end

  def self.default_admin
    admin.first
  end

  def self.default_doctor
    doctor.first
  end

  def to_s
    "#{first_name} #{last_name}"
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/messages_controller.rb
# frozen_string_literal: true

class MessagesController < ApplicationController
  def show
    @message = Message.find(params[:id])
    @message.update_attribute(:read, true)

    fresh_when last_modified: @message.updated_at.utc, etag: @message
  end

  def new
    @message = Message.new(
      inbox_id: params[:outbox_id],
      outbox_id: params[:inbox_id]
    )
  end

  def create
    @message = Message.new(message_params)
    if @message.save
      flash[:notice] = "Message: #{@message.body.truncate(70, separator: ' ')} sent to #{@message.inbox.user}"
      redirect_to messages_path
    else
      render :new
    end
  end

  private

  def message_params
    params.require(:message).permit(:outbox_id, :inbox_id, :body)
  end
end

app/controllers/payments_controller.rb
# frozen_string_literal: true

class PaymentsController < ApplicationController
  def create
    message = Message.find(payment_params[:message_id])
    patient = User.current
    User.default_admin.inbox_messages.create(
      outbox_id: patient.outbox.id,
      body: "I've lost my prescription. Please generate and send me another one. I've paid"
    )
    payment = patient.payments.create(mode: payment_params[:mode])
    payment.checkout(payment_params[:key])
    message.touch
    flash[:notice] = 'Request to generate new prescription was sent to Admin. Thank You!'
    redirect_to messages_path
  end

  private

  def payment_params
    params.require(:payment).permit(:message_id, :mode, :key)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/payments_helper.rb
# frozen_string_literal: true

module PaymentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>patient-doctor-admin</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="bg-light">
    <%= render 'layouts/application/header' %>

    <main role="main" class="container">
      <%= render "layouts/application/flash" if flash[:notice] %>
      <%= yield %>
    </main>
  </body>
</html>

app/views/layouts/application/_flash.html.erb
<div class="my-3 p-3 bg-white rounded shadow-sm">
  <h6 class="border-gray pb-2 mb-0">Notice</h6>
  <p><%= flash[:notice] %></p>
</div>

app/views/layouts/application/_header.html.erb
<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
  <a class="navbar-brand" href="#">patient-doctor-admin</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarsExampleDefault">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to messages_path, class: 'nav-link' do %>
          Inbox
        <% end  %>
      </li>
    </ul>
  </div>
</nav>

app/views/messages/index.html.erb
<div class="container">
  <div class="row">
    <div class="my-3 col-sm p-3 m-2 bg-white rounded shadow-sm">
      <h6 class="border-bottom border-gray pb-2 mb-0">
        Inbox <strong>Patient</strong> <small><%= User.current %></small>
      </h6>
      <%= render partial: "messages/index/message", collection: User.current.inbox_messages %>
    </div>
    <div class="my-3 col-sm p-3 m-2 bg-white rounded shadow-sm">
      <h6 class="border-bottom border-gray pb-2 mb-0">
        <% doctor = User.default_doctor %>
        Inbox <strong>Doctor</strong> <small><%= doctor %> | Unread: <%= doctor.inbox.messages_unread_counter %></small>
      </h6>
      <%= render partial: "messages/index/message", collection: User.default_doctor.inbox_messages %>
    </div>
    <div class="my-3 col-sm p-3 m-2 bg-white rounded shadow-sm">
      <h6 class="border-bottom border-gray pb-2 mb-0">
        Inbox <strong>Admin</strong> <small><%= User.default_admin %></small>
      </h6>
      <%= render partial: "messages/index/message", collection: User.default_admin.inbox_messages %>
    </div>
  </div>
</div>

app/views/messages/index/_message.html.erb
<%= link_to message do %>
  <div class="media text-muted pt-3">
    <svg class="bd-placeholder-img mr-2 rounded" width="32" height="32" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: 32x32"><title>Placeholder</title><rect width="100%" height="100%" fill="#007bff"></rect><text x="50%" y="50%" fill="#007bff" dy=".3em">32x32</text></svg>
    <p class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
      <strong class="d-block text-gray-dark"><%= message.outbox.user.first_name %> <%= message.outbox.user.last_name %></strong>
      <%= message.body.truncate(45) %>
    </p>
  </div>
<% end %>

app/views/messages/new.html.erb
<div class="card mt-3">
  <h5 class="card-header">
    Reply
  </h5>
  <div class="card-body">
    <%= form_for @message do |f| %>
      <%= f.hidden_field :inbox_id, value: @message.inbox_id %>
      <%= f.hidden_field :outbox_id, value: @message.outbox_id %>
      <div class="form-group py-3">
        <%= f.text_area :body, class: "form-control", rows: 3 %>
      </div>

      <div class="form-group mb-0 text-right">
        <%= f.submit 'Send Message', class: 'btn btn-primary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/messages/show.html.erb
<div class="card my-3 ">
  <h5 class="card-header">
    <strong>From:</strong>
    <%= "Dr." if @message.outbox.user.is_doctor? %>
    <%= @message.outbox.user %>
  </h5>

  <div class="card-body">
    <p class="card-text"><%= @message.body %></p>
    <% @message.outbox.user %>
    <div class="btn-group mb-2" role="group">
      <%= link_to "Reply", new_message_path(inbox_id: @message.inbox_id, outbox_id: @message.outbox_id), class: "btn btn-primary" %>
      <%= form_tag payments_path do %>
        <%= hidden_field_tag "payment[message_id]", @message.id %>
        <%= hidden_field_tag "payment[mode]", "debit_card" %>
        <%= hidden_field_tag "payment[key]", Digest::SHA1.hexdigest("prescription") %>
        <%= submit_tag "I've lost my prescription", class: "btn btn-primary" %>
      <% end %>
    </div>
    <p class="card-text">
      Message read? <%= @message.read %>
    </p>
  </div>
</div>